# Generated by Django 5.1.5 on 2025-01-29 02:54

import apps.farmer.services.farmer_service
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Agricultor')),
                ('document', models.CharField(max_length=200, unique=True, validators=[apps.farmer.services.farmer_service.validate_cpf_cnpj], verbose_name='CPF/CNPJ')),
                ('type_document', models.CharField(max_length=10, verbose_name='Tipo do Documento')),
                ('deleted', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='farmer_address', to='address.addressfarmermodel', verbose_name='Endereço do Fazendeiro')),
            ],
            options={
                'verbose_name': 'Fazendeiro',
                'verbose_name_plural': 'Fazendeiros',
                'db_table': 'farmer',
            },
        ),
    ]
