# Generated by Django 5.1.5 on 2025-01-29 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropsPlantedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(choices=[('soja', 'Soja'), ('cafe', 'Café'), ('cana_de_acucar', 'Cana-de-açúcar'), ('arroz', 'Arroz'), ('milho', 'Milho')], default='soja', max_length=20, verbose_name='Produto')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='crops_planted_farm', to='farm.farmmodel', verbose_name='Fazenda')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='crops_planted_harvest', to='harvest.harvestmodel', verbose_name='Safra')),
            ],
            options={
                'verbose_name': 'Cultura Plantada',
                'verbose_name_plural': 'Culturas Plantadas',
                'db_table': 'crops_planted',
            },
        ),
    ]
